--------------------------------------------------------
--  DDL for Table AWC_DUMMY_TBL_2
--------------------------------------------------------

CREATE TABLE AWC_DUMMY_TBL_2
(PO_XREF_ID        NUMBER,
 FLOW_ID            VARCHAR2(100),
 FILE_NAME          VARCHAR2(250),
 SentLoc            VARCHAR2(250),
 BillOfLading       VARCHAR2(250),
 Pallet		    VARCHAR2(250),
 RecNo		    VARCHAR2(250),
 Type		    VARCHAR2(250),
 Action  	    VARCHAR2(250),
 UpldDate	    VARCHAR2(250),
 BuyEnt             VARCHAR2(250),
 PONum              VARCHAR2(250),
 POLine             VARCHAR2(250),
 POPallet           VARCHAR2(250),
 POBlnktRel         VARCHAR2(250),
 POPackSlip         VARCHAR2(250),
 POItemCtlg         VARCHAR2(250),
 POItem             VARCHAR2(250),
 POUom              VARCHAR2(250),
 PODelDate          VARCHAR2(250),
 POQtyr             VARCHAR2(250),
 POCarr             VARCHAR2(250),
 POOrig             VARCHAR2(250),
 POBol              VARCHAR2(250),
 POWeight           VARCHAR2(250),
 PONotes            VARCHAR2(250),
 ULDT               VARCHAR2(250),
 Processed          VARCHAR2(250),
 Complete           VARCHAR2(250),
 UserID             VARCHAR2(250),
 PutAwayHold        VARCHAR2(250),
 ReceivedDate       VARCHAR2(250),
 ShippedDate        VARCHAR2(250),
 CREATION_DATE      TIMESTAMP,
 CREATED_BY         VARCHAR2(250),
 LAST_UPDATE_DATE   TIMESTAMP,
 LAST_UPDATED_BY    VARCHAR2(250),
 ERROR_TYPE      VARCHAR2(500) , 
STATUS    VARCHAR2(10),
MESSAGE    VARCHAR2(4000),
 CONSTRAINT DUMMY_XREF_ID_PK PRIMARY KEY (PO_XREF_ID));
